# Generated by Django 4.2.23 on 2025-08-16 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nipd', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nisn', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('no_siswa', models.CharField(max_length=20)),
                ('no_ortu', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuptk', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField(max_length=200)),
                ('no_hp', models.CharField(max_length=20)),
                ('guru', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='akademik.userguru')),
            ],
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('waktu', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alpha')], max_length=1)),
                ('keterangan', models.TextField(max_length=200)),
                ('bukti', models.ImageField(blank=True, null=True, upload_to='bukti_presensi/')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
        ),
        migrations.AddField(
            model_name='kelas',
            name='guru',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='akademik.userguru'),
        ),
    ]
