# Generated by Django 4.2.23 on 2025-08-16 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=5)),
                ('nama_mapel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GuruMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_guru_mapel', models.CharField(max_length=6)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.userguru')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.mapel')),
            ],
        ),
        migrations.AddField(
            model_name='userguru',
            name='mengajar',
            field=models.ManyToManyField(through='akademik.GuruMapel', to='akademik.mapel'),
        ),
    ]
