# Generated by Django 4.2.23 on 2025-08-16 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_mapel_gurumapel_userguru_mengajar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jam', models.CharField(max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_akhir', models.TimeField()),
                ('durasi', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PresensiSiswa',
            new_name='PresensiSekolah',
        ),
        migrations.CreateModel(
            name='PresensiMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('waktu', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alpha')], max_length=1)),
                ('keterangan', models.TextField(max_length=200)),
                ('bukti', models.ImageField(blank=True, null=True, upload_to='bukti_presensi/')),
                ('guru_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.gurumapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perihal', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('selesai', 'Selesai')], max_length=10)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.userguru')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('guru_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.gurumapel')),
                ('jampel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.jampelajaran')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
            ],
        ),
    ]
