# Generated by Django 4.2.23 on 2025-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_jampelajaran_rename_presensisiswa_presensisekolah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jampelajaran',
            name='durasi',
            field=models.CharField(max_length=10),
        ),
    ]
