# Generated by Django 4.2.23 on 2025-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_alter_jampelajaran_durasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguru',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Guru', 'Guru')], max_length=10),
        ),
    ]
