# Generated by Django 4.2.23 on 2025-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_alter_userguru_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gurumapel',
            old_name='kode_guru_mapel',
            new_name='kode_ajar',
        ),
        migrations.AddField(
            model_name='profileguru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_guru/'),
        ),
    ]
