# Generated by Django 4.2.23 on 2025-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_rename_kode_guru_mapel_gurumapel_kode_ajar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='nama_wali',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
