# Generated by Django 4.2.23 on 2025-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_siswa_nama_wali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama_wali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nipd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='no_ortu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='no_siswa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
