# Generated by Django 4.2.23 on 2025-08-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_alter_siswa_nama_ayah_alter_siswa_nama_ibu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='guru',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.userguru'),
        ),
    ]
