# Generated by Django 4.2.23 on 2025-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0009_alter_kelas_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
