# Generated by Django 4.2.23 on 2025-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0010_alter_kelas_nama_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='nama_grup_wa',
            field=models.CharField(blank=True, help_text='Nama Grup WA harus persis (Case Sensitive)', max_length=255, null=True),
        ),
    ]
